### ISSUE TITLE
Feature: add Date-Millisecond http header to builder bid / relay header request

### ISSUE THREAD

**Issue by alextes** [attestantio/vouch#292]
i think vouch refers to these as builder bids. the builder spec calls them "headers".
either way, the request is to add a HTTP header on those requests indicating the timestamp the request was sent.

relays would use this to measure proposer latency, which helps them return the response in time.

details in: https://github.com/ethereum/builder-specs/issues/106

spec: https://github.com/ethereum/builder-specs/blob/1bbe1e299aa174aa6b7ec7a84c59c678b4e1b063/apis/builder/header.yaml#L35

the relevant bit is:
```yaml
- name: Date-Milliseconds
  in: header
  required: false
  description: |
    Optional header containing a Unix timestamp in milliseconds representing
    the point-in-time the request was sent. This header can be used to measure
    latency.
  schema:
    type: integer
    format: int64
    example: 1710338135000
```
